# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFinaltest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_finaltest(self):
    self.driver.get("https://hnbgu.ac.in/")
    self.driver.set_window_size(932, 1060)
    self.driver.find_element(By.CSS_SELECTOR, ".notif-listed > .more-link > a").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "File").click()
    self.vars["win4686"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win4686"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .pdf-file").click()
    self.vars["win8776"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win8776"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .pdf-file").click()
    self.vars["win4265"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win4265"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) .pdf-file").click()
    self.vars["win3118"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win3118"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) .pdf-file").click()
    self.vars["win4455"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win4455"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) .pdf-file").click()
    self.vars["win9990"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win9990"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(8) .pdf-file").click()
    self.vars["win4551"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win4551"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(10) .pdf-file").click()
    self.vars["win167"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win167"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".upevent-listed > .more-link > a").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "File").click()
    self.vars["win2932"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win2932"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".col-2 > .views-field-field-event-upload-file > .field-content").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".col-2 .pdf-file").click()
    self.vars["win6882"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6882"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".col-3 .pdf-file").click()
    self.vars["win8701"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win8701"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.close()
  
